### ISSUE TITLE
At first operator input: missing screenprint

### ISSUE THREAD

**Issue by hjaltebaekgaard** [FredMar/2.sem-CDIO-2#5]
The first time the program is run after starting the weight simulator the text for the operator confirmation (j/n) inquiry doesn't appear.

**Comment by hjaltebaekgaard** [comment]
It still does this for me. Try closing the weight simulator, open it without touching anything, start the client program, type the correct ID (12) in first try and see if the text from "svar = getOtherInput("Hej, er " + operatorName + " dit navn (j/n)");" appears on the weight display.

**Comment by hjaltebaekgaard** [comment]
It seems to remove the issue if you call resetDisplay() before starting the procedure. But I am not sure of what's actually happening when you start the weightsimulator.

**Comment by kimsand123** [comment]
ok ill look into it some more.
